# Generated by Django 3.1.3 on 2021-05-08 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('Female', 'Female')], max_length=10, null=False)),
                ('mbti', models.CharField(blank=True, choices=[('istp', 'ISTP'), ('infj', 'INFJ'), ('estj', 'ESTJ'), ('isfj', 'ISFJ'), ('entj', 'ENTJ'), ('enfp', 'ENFP'), ('entp', 'ENTP'), ('esfp', 'ESFP'), ('istj', 'ISTJ'), ('estp', 'ESTP'), ('esfj', 'ESFJ'), ('enfj', 'ENFJ'), ('intp', 'INTP'), ('isfp', 'ISFP'), ('infp', 'INFP'), ('intj', 'INTJ')], max_length=10, null=True)),
                ('area1', models.CharField(blank=True, max_length=100, null=True)),
                ('area2', models.CharField(blank=True, max_length=100, null=True)),
                ('area3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
