# Generated by Django 3.1.2 on 2021-05-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('gender', models.BooleanField(null=True)),
                ('mbti', models.CharField(max_length=5)),
                ('area1', models.CharField(blank=True, max_length=50, null=True)),
                ('area2', models.CharField(blank=True, max_length=50, null=True)),
                ('area3', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
