# Generated by Django 3.1.2 on 2021-05-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210506_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('male', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='mbti',
            field=models.CharField(choices=[('esfj', 'ESFJ'), ('istj', 'ISTJ'), ('infj', 'INFJ'), ('istp', 'ISTP'), ('esfp', 'ESFP'), ('intp', 'INTP'), ('estp', 'ESTP'), ('estj', 'ESTj'), ('isfp', 'ISFP'), ('entp', 'ENTP'), ('intj', 'INTJ'), ('enfj', 'ENFJ'), ('enfp', 'ENFP'), ('isfj', 'ISFJ'), ('entj', 'ENTJ'), ('infp', 'INFP')], max_length=10),
        ),
    ]
