# Generated by Django 3.2.3 on 2021-07-22 15:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 15, 20, 18, 506012, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
