# Generated by Django 3.1.2 on 2021-08-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='EMAIL ID', max_length=64, unique=True, verbose_name='email id')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('jobfamily', models.CharField(max_length=400)),
                ('job', models.CharField(max_length=400)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
