# Generated by Django 3.1.2 on 2021-08-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
