# Generated by Django 3.2.3 on 2021-05-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0002_alter_user_mbti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='mbti',
            field=models.CharField(blank=True, choices=[('infj', 'INFJ'), ('enfp', 'ENFP'), ('estp', 'ESTP'), ('istp', 'ISTP'), ('intj', 'INTJ'), ('infp', 'INFP'), ('entj', 'ENTJ'), ('intp', 'INTP'), ('enfj', 'ENFJ'), ('isfp', 'ISFP'), ('isfj', 'ISFJ'), ('estj', 'ESTJ'), ('entp', 'ENTP'), ('esfp', 'ESFP'), ('istj', 'ISTJ'), ('esfj', 'ESFJ')], max_length=10, null=True),
        ),
    ]
