# Generated by Django 3.2.3 on 2021-06-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0004_alter_user_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mbti',
            field=models.CharField(blank=True, choices=[('enfp', 'ENFP'), ('istj', 'ISTJ'), ('esfj', 'ESFJ'), ('esfp', 'ESFP'), ('infj', 'INFJ'), ('isfj', 'ISFJ'), ('infp', 'INFP'), ('estj', 'ESTJ'), ('intp', 'INTP'), ('entp', 'ENTP'), ('istp', 'ISTP'), ('enfj', 'ENFJ'), ('entj', 'ENTJ'), ('isfp', 'ISFP'), ('intj', 'INTJ'), ('estp', 'ESTP')], max_length=10, null=True),
        ),
    ]
